# Generated by Django 3.0.5 on 2020-05-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
