# Generated by Django 3.0.5 on 2020-05-29 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bundle', '0001_initial'),
        ('wmslayer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wmslayer.WMSLayer'),
        ),
    ]
