# Generated by Django 3.0.5 on 2020-05-30 00:32

from django.db import migrations

def create_bundle(apps, schema_editor):
    Bundle = apps.get_model('bundle', 'Bundle')
    WMSLayer = apps.get_model('wmslayer', 'WMSLayer')
    BundleLayer = apps.get_model('bundle', 'BundleLayer')

    values = [
            (
                'Албан хэрэгцээний багц',
                0,
                False
            ),
            (
                'Олон нийтэд зориулсан багц',
                0,
                False
            ), 
        ]

    for name, price, is_removeable in values:
        bundle = Bundle.objects.create(
            name=name,
            price=price,
            is_removeable=is_removeable)

        for wmslayer in WMSLayer.objects.all():
            bundle.layer.add(wmslayer)

class Migration(migrations.Migration):

    dependencies = [
        ('bundle', '0003_auto_20200529_2104'),
    ]

    operations = [
        migrations.RunPython(create_bundle)
    ]

