# Generated by Django 3.0.5 on 2020-05-30 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bundle', '0005_auto_20200530_2021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bundle',
            options={'ordering': ('created_at',)},
        ),
    ]
