# Generated by Django 3.0.5 on 2020-05-29 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WMSLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wms', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wms.WMS')),
            ],
        ),
    ]
