# Generated by Django 3.0.5 on 2020-05-30 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wms',
            options={'ordering': ('created_at',)},
        ),
    ]
